<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>annotations</Nullable>
    <UseWPF>True</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>GHelper.WPF</AssemblyName>
    <RootNamespace>GHelper.WPF</RootNamespace>
    <DebugType>embedded</DebugType>
    <OutputPath>bin\x64\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\x64\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GHelper.Shared\GHelper.Shared.csproj" />
  </ItemGroup>

</Project>
